nav:
- Home: index.md
- Bigfunctions:
  - bigfunctions/README.md
  - Load Data:
    - bigfunctions/load/README.md
    - bigfunctions/exchange_rate.md
    - bigfunctions/faker.md
    - bigfunctions/get.md
    - bigfunctions/get_appstore_reviews.md
    - bigfunctions/get_data_from_apify.md
    - bigfunctions/get_github_data.md
    - bigfunctions/get_google_trends.md
    - bigfunctions/get_json.md
    - bigfunctions/get_meteo.md
    - bigfunctions/get_playstore_reviews.md
    - bigfunctions/get_transport_emissions.md
    - bigfunctions/get_webpage_data.md
    - bigfunctions/get_webpage_metadata.md
    - bigfunctions/get_webpage_structured_data.md
    - bigfunctions/list_public_datasets.md
    - bigfunctions/load_api_data.md
    - bigfunctions/load_duckdb_database.md
    - bigfunctions/load_duckdb_database_into_temp_dataset.md
    - bigfunctions/load_file.md
    - bigfunctions/load_file_into_temp_dataset.md
    - bigfunctions/load_google_trends.md
    - bigfunctions/load_saas_data.md
    - bigfunctions/load_saas_data_into_temp_dataset.md
  - Transform:
    - bigfunctions/transform/README.md
    - Transform Numeric:
      - bigfunctions/transform/transform_numeric/README.md
      - bigfunctions/compute_linear_regression_coefficients.md
      - bigfunctions/format_percentage.md
      - bigfunctions/nps.md
      - bigfunctions/quantize_into_bins.md
      - bigfunctions/quantize_into_bins_with_labels.md
      - bigfunctions/quantize_into_fixed_width_bins.md
      - bigfunctions/weighted_average.md
    - Convert Data Format:
      - bigfunctions/transform/convert_data_format/README.md
      - bigfunctions/html2pdf.md
      - bigfunctions/json2excel.md
      - bigfunctions/json2xml.md
      - bigfunctions/xml2json.md
    - Machine Learning:
      - bigfunctions/transform/machine_learning/README.md
      - bigfunctions/precision_recall_auc.md
      - bigfunctions/precision_recall_curve.md
      - bigfunctions/prophet.md
      - bigfunctions/prophet_table.md
      - bigfunctions/roc_auc.md
      - bigfunctions/roc_curve.md
      - bigfunctions/sentiment_score.md
    - Transform Array:
      - bigfunctions/transform/transform_array/README.md
      - bigfunctions/are_arrays_equal.md
      - bigfunctions/array_contains.md
      - bigfunctions/array_intersect.md
      - bigfunctions/array_union.md
      - bigfunctions/benford_distance.md
      - bigfunctions/distinct_values.md
      - bigfunctions/find_greater_value.md
      - bigfunctions/find_lower_value.md
      - bigfunctions/find_value.md
      - bigfunctions/frequent_values.md
      - bigfunctions/get_value.md
      - bigfunctions/last_value.md
      - bigfunctions/max_value.md
      - bigfunctions/median_value.md
      - bigfunctions/min_max_scaler.md
      - bigfunctions/min_value.md
      - bigfunctions/percentile_value.md
      - bigfunctions/rare_values.md
      - bigfunctions/remove_value.md
      - bigfunctions/sort_values.md
      - bigfunctions/sort_values_desc.md
      - bigfunctions/sum_values.md
      - bigfunctions/z_scores.md
    - Transform Date:
      - bigfunctions/transform/transform_date/README.md
      - bigfunctions/date_sub_isoyear.md
      - bigfunctions/generate_dates.md
      - bigfunctions/gregorian2hijri.md
      - bigfunctions/is_public_holiday.md
      - bigfunctions/parse_date.md
      - bigfunctions/translated_month_name.md
      - bigfunctions/translated_weekday_name.md
    - Transform String:
      - bigfunctions/transform/transform_string/README.md
      - bigfunctions/camel2snake.md
      - bigfunctions/convert_non_ascii_characters_to_unicode_escape_sequences.md
      - bigfunctions/deidentify.md
      - bigfunctions/detect_language.md
      - bigfunctions/detect_sensitive_info.md
      - bigfunctions/is_email_valid.md
      - bigfunctions/is_phone_number_valid.md
      - bigfunctions/markdown2html.md
      - bigfunctions/ngram_frequency_similarity.md
      - bigfunctions/parse_url.md
      - bigfunctions/parse_user_agent.md
      - bigfunctions/phone_number_info.md
      - bigfunctions/remove_accents.md
      - bigfunctions/remove_extra_whitespaces.md
      - bigfunctions/remove_strings.md
      - bigfunctions/remove_words.md
      - bigfunctions/render_handlebars_template.md
      - bigfunctions/render_template.md
      - bigfunctions/replace_special_characters.md
      - bigfunctions/translate.md
      - bigfunctions/url_decode.md
      - bigfunctions/xml_extract.md
    - Transform Geo Data:
      - bigfunctions/transform/transform_geo_data/README.md
      - bigfunctions/geocode.md
      - bigfunctions/geocode_fr.md
      - bigfunctions/h3.md
      - bigfunctions/reverse_geocode.md
      - bigfunctions/validate_address.md
    - Transform Ip:
      - bigfunctions/transform/transform_ip/README.md
      - bigfunctions/ip2asn.md
      - bigfunctions/ip2continent.md
      - bigfunctions/ip2continent_name.md
      - bigfunctions/ip2country.md
      - bigfunctions/ip2country_name.md
      - bigfunctions/ip_range2ip_networks.md
    - Graph:
      - bigfunctions/transform/graph/README.md
      - bigfunctions/connected_components.md
    - AI:
      - bigfunctions/transform/ai/README.md
      - bigfunctions/ask_ai.md
      - bigfunctions/ask_appstore_reviews.md
      - bigfunctions/ask_my_data.md
      - bigfunctions/categorize.md
      - bigfunctions/classify_text.md
      - bigfunctions/generate_categories.md
      - bigfunctions/generate_face_embedding.md
      - bigfunctions/generate_sql.md
    - Transform Json:
      - bigfunctions/transform/transform_json/README.md
      - bigfunctions/create_materialized_view_w_flattened_json_column.md
      - bigfunctions/items2json.md
      - bigfunctions/json_column_schema.md
      - bigfunctions/json_items.md
      - bigfunctions/json_keys.md
      - bigfunctions/json_merge.md
      - bigfunctions/json_query.md
      - bigfunctions/json_schema.md
      - bigfunctions/json_values.md
      - bigfunctions/sql_to_flatten_json_column.md
    - GA:
      - bigfunctions/transform/ga4/README.md
      - bigfunctions/create_ga4_views.md
  - Take Actions:
    - bigfunctions/take_actions/README.md
    - Notify:
      - bigfunctions/take_actions/notify/README.md
      - bigfunctions/send_google_chat_message.md
      - bigfunctions/send_mail.md
      - bigfunctions/send_mail_with_excel.md
      - bigfunctions/send_mail_with_gmail.md
      - bigfunctions/send_mail_with_sendgrid.md
      - bigfunctions/send_slack_message.md
      - bigfunctions/send_sms.md
      - bigfunctions/send_teams_message.md
    - Trigger Event:
      - bigfunctions/take_actions/trigger_event/README.md
      - bigfunctions/refresh_powerbi.md
      - bigfunctions/refresh_tableau.md
    - Export:
      - bigfunctions/take_actions/export/README.md
      - bigfunctions/export_table_to_datastore.md
      - bigfunctions/export_to_datastore.md
      - bigfunctions/export_to_pubsub.md
      - bigfunctions/post.md
      - bigfunctions/upload_table_to_gsheet.md
      - bigfunctions/upload_to_gsheet.md
  - Utils:
    - bigfunctions/utils/README.md
    - bigfunctions/deduplicate_rows.md
    - bigfunctions/delete_temp_datasets.md
    - bigfunctions/get_latest_partition_timestamp.md
    - bigfunctions/get_table_columns.md
    - bigfunctions/get_view_history.md
    - bigfunctions/list_scheduled_queries.md
    - bigfunctions/run_python.md
    - bigfunctions/sleep.md
    - bigfunctions/timestamp_from_unix_date_time.md
    - bigfunctions/timestamp_to_unix_date_time.md
    - bigfunctions/upsert.md
- Framework: framework.md
- Community:
  - Join the Community: community.md
  - Join Slack: https://join.slack.com/t/unytics/shared_invite/zt-1gbv491mu-cs03EJbQ1fsHdQMcFN7E1Q
  - Add a star on GitHub: https://github.com/unytics/bigfunctions
  - Suggest a function: https://github.com/unytics/bigfunctions/issues/new?assignees=&labels=new-bigfunction&projects=&template=0_new_bigfunction.yaml&title=%5Bnew%5D%3A+%60function_name%28argument1%2C+argument2%29%60
  - Report a bug: https://github.com/unytics/bigfunctions/issues/new/choose
- Blog: blog/index.md
- Partner with us: chat_with_us.md
